# 4 Numpy基础

## 4.1 Numpy ndarray:多维数组对象

In [1]:
import numpy as np

data=np.random.randn(2,3)
data

array([[-2.6787259 , -0.26064671, -1.2811899 ],
       [-0.39552118, -0.51238433,  1.0513284 ]])

In [2]:
data*10

array([[-26.78725897,  -2.60646712, -12.81189901],
       [ -3.95521178,  -5.12384332,  10.513284  ]])

In [3]:
data+data

array([[-5.35745179, -0.52129342, -2.5623798 ],
       [-0.79104236, -1.02476866,  2.1026568 ]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

### 4.1.1 生成ndarray

In [6]:
data1=[6,7.5,8,0,1]

arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2=[[1,2,3,4],[5,6,7,8]]

arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
#使用np.empty有时会返回垃圾数值
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

In [14]:
np.full_like(arr2,10086)

array([[10086, 10086, 10086, 10086],
       [10086, 10086, 10086, 10086]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
#arange是Numpy版的range
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 4.1.2 ndarray的数据类型

In [17]:
arr3=np.array([1,2,3,4,5])
float_arr=arr3.astype(np.float64)
float_arr.dtype

dtype('float64')

In [18]:
arr4=np.array([3.7,-1.2,-2.6,.5,12.9,10.1])
arr4.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [19]:
str_arr=np.array(['1.25','-9.6','42'])
str_arr.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [20]:
arr4.astype(str_arr.dtype)

array(['3.7', '-1.2', '-2.6', '0.5', '12.9', '10.1'], dtype='<U4')

### 4.1.3 Numpy数组算术

In [21]:
arr5=np.array([[1,2,3],[4,5,6]])
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr5*arr5

array([[ 1,  4,  9],
       [16, 25, 36]])

In [23]:
arr5-arr5

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
1/arr5

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [25]:
arr5**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [26]:
arr6=np.array([[0,4,1],[7,2,12]])
arr6>arr5

array([[False,  True, False],
       [ True, False,  True]])

In [27]:
#切片时原数组的视图
#改变切片。改变原数组
arr7=np.arange(10)
slices=arr7[5:8]
slices[1]=12345
arr7

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [28]:
slices[:]=64
arr7

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [29]:
#如果你想拷贝而非视图，需要显示声明
slices_copy=arr7[5:8].copy()
slices_copy[:]=32
arr7

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [30]:
slices_copy

array([32, 32, 32])

### 4.1.5 布尔索引

In [31]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

bools=names=='Bob'
bools

array([ True, False, False,  True, False, False, False])

In [32]:
data=np.random.randn(7,4)

data

array([[ 0.14713181,  0.76274972,  0.38667772, -0.64630979],
       [ 1.06772256,  0.50497391,  0.35089248, -0.35871126],
       [-0.50796238,  0.19728918, -1.73497135, -1.08817798],
       [-0.69440594, -1.29418087,  1.97671163,  0.57337584],
       [ 1.24400954, -0.41236073, -1.12748101, -1.54343888],
       [ 1.06054042,  0.24134244,  1.34833965,  0.57705435],
       [-0.57358086, -0.58585213,  0.32041437,  0.90222226]])

In [33]:
data[bools,2:]

array([[ 0.38667772, -0.64630979],
       [ 1.97671163,  0.57337584]])

In [34]:
data[names!='Bob']

array([[ 1.06772256,  0.50497391,  0.35089248, -0.35871126],
       [-0.50796238,  0.19728918, -1.73497135, -1.08817798],
       [ 1.24400954, -0.41236073, -1.12748101, -1.54343888],
       [ 1.06054042,  0.24134244,  1.34833965,  0.57705435],
       [-0.57358086, -0.58585213,  0.32041437,  0.90222226]])

In [35]:
#使用~对一个条件取反
data[~(names=='Bob')]

array([[ 1.06772256,  0.50497391,  0.35089248, -0.35871126],
       [-0.50796238,  0.19728918, -1.73497135, -1.08817798],
       [ 1.24400954, -0.41236073, -1.12748101, -1.54343888],
       [ 1.06054042,  0.24134244,  1.34833965,  0.57705435],
       [-0.57358086, -0.58585213,  0.32041437,  0.90222226]])

In [36]:
data[data<0]=0
data

array([[0.14713181, 0.76274972, 0.38667772, 0.        ],
       [1.06772256, 0.50497391, 0.35089248, 0.        ],
       [0.        , 0.19728918, 0.        , 0.        ],
       [0.        , 0.        , 1.97671163, 0.57337584],
       [1.24400954, 0.        , 0.        , 0.        ],
       [1.06054042, 0.24134244, 1.34833965, 0.57705435],
       [0.        , 0.        , 0.32041437, 0.90222226]])

In [37]:
data[names!='Joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.06772256, 0.50497391, 0.35089248, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.06054042, 0.24134244, 1.34833965, 0.57705435],
       [0.        , 0.        , 0.32041437, 0.90222226]])

In [38]:
#综合两个条件
condition1=data<10
condition2=names!='Joe'
union=(condition1.T&condition2).T
data[union]=9
data

array([[9.        , 9.        , 9.        , 9.        ],
       [1.06772256, 0.50497391, 0.35089248, 0.        ],
       [9.        , 9.        , 9.        , 9.        ],
       [9.        , 9.        , 9.        , 9.        ],
       [9.        , 9.        , 9.        , 9.        ],
       [1.06054042, 0.24134244, 1.34833965, 0.57705435],
       [0.        , 0.        , 0.32041437, 0.90222226]])

### 4.1.6 神奇索引

In [39]:
#神奇索引得到一维数组
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [40]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [41]:
arr[[1,5,7,2],0]

array([ 4, 20, 28,  8])

In [42]:
#行列的子集得到的矩阵
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 4.1.7 数组转置和换轴

In [43]:
arr=np.random.randn(6,3)
arr

array([[-0.08281738, -0.99461656, -0.82703608],
       [ 0.60001225,  0.93662413, -0.25337226],
       [ 0.52452399,  0.422585  , -0.03761161],
       [-1.89993765,  1.12280001, -1.19417743],
       [ 0.8422699 ,  1.08197886, -0.88107689],
       [ 1.83519529, -1.19174621,  0.71496639]])

In [44]:
arr.dot(arr.T)

array([[ 1.68010949, -0.77172531, -0.43264358,  0.02822018, -0.4172263 ,
         0.44204146],
       [-0.77172531,  1.30147697,  0.72005386,  0.21422715,  1.74202021,
        -0.19623125],
       [-0.43264358,  0.72005386,  0.45511813, -0.4771695 ,  0.93215752,
         0.43209885],
       [ 0.02822018,  0.21422715, -0.4771695 ,  6.29650268,  0.66674772,
        -5.67864603],
       [-0.4172263 ,  1.74202021,  0.93215752,  0.66674772,  2.65639333,
        -0.37365482],
       [ 0.44204146, -0.19623125,  0.43209885, -5.67864603, -0.37365482,
         5.29937774]])

In [45]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [46]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [47]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 通用函数： 快速的逐元素数组函数

In [48]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [50]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [51]:
x=np.random.randn(8)
y=np.random.randn(8)
x

array([ 0.24284911,  1.13705885, -1.20809664,  1.33633763, -0.21842259,
        0.76651242, -0.31887255, -0.13272202])

In [52]:
y

array([-0.36791815,  0.56884801,  0.80256573, -0.31908849, -0.98602489,
       -0.12882486,  0.36020116, -0.95432652])

In [53]:
np.maximum(x,y)

array([ 0.24284911,  1.13705885,  0.80256573,  1.33633763, -0.21842259,
        0.76651242,  0.36020116, -0.13272202])

In [54]:
arr=np.random.randn(7)*5
arr

array([ 7.05574067, -5.13469123, -1.96858611,  8.32729026, -2.97105956,
        5.25604726, 10.409648  ])

In [55]:
remainder,whole_part=np.modf(arr)
remainder

array([ 0.05574067, -0.13469123, -0.96858611,  0.32729026, -0.97105956,
        0.25604726,  0.409648  ])

In [56]:
whole_part

array([ 7., -5., -1.,  8., -2.,  5., 10.])

## 4.3 使用数组进行面向数组编程

In [57]:
points=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(points,points)
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [58]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [59]:
z=np.sqrt(xs**2+ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

### 4.3.1 将条件逻辑作为数组操作

In [60]:
#列表推导式的不足,仅限一维

xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
[(x if c else y)
 for x,y,c in zip(xarr,yarr,cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [61]:
#使用np.where进行条件逻辑选择

np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [62]:
arr=np.random.randn(4,4)
np.where(arr>0,2,-2)

array([[ 2, -2,  2,  2],
       [-2,  2, -2,  2],
       [-2,  2, -2,  2],
       [ 2, -2, -2, -2]])

In [63]:
np.where(arr>0,2,arr)

array([[ 2.        , -0.39641363,  2.        ,  2.        ],
       [-1.09850599,  2.        , -1.16367792,  2.        ],
       [-0.73226771,  2.        , -0.66085756,  2.        ],
       [ 2.        , -1.50209945, -0.77088159, -0.65899423]])

### 4.3.2 数学和统计方法

In [64]:
arr=np.random.randn(5,4)
arr.mean()

0.1219733620134976

In [65]:
np.mean(arr)

0.1219733620134976

In [66]:
arr.sum()

2.439467240269952

In [67]:
arr.mean(axis=1)

array([ 0.80436227, -0.54598755,  0.43352673,  0.0446079 , -0.12664255])

In [68]:
arr.sum(axis=0)

array([-0.55662339,  0.63529396,  1.23167833,  1.12911834])

In [69]:
arr=np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [71]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [72]:
arr.max(axis=1)

array([2, 5, 8])

In [73]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [74]:
arr.std(ddof=1)

2.7386127875258306

### 4.3.3 布尔值数组的方法

In [75]:
#计算正数的个数

arr=np.random.randn(100)
(arr>0).sum()

49

In [76]:
#any检查是否存在True
#all检查是否全为True

bools=np.array([False,False,True,False])

bools.any()

True

In [77]:
bools.all()

False

### 4.3.4 排序

In [78]:
arr=np.random.randn(6)
arr.sort()
arr

array([-1.15831447, -0.84242364, -0.51714776,  0.02253231,  0.74606837,
        2.16370323])

In [79]:
#使用np.sort对元素组的拷贝排序

arr=np.random.randn(5,3)
arr

array([[ 0.72639504, -0.41702291, -0.93311551],
       [ 0.87238245,  0.79619449, -0.42956273],
       [ 2.15452682, -1.18853185,  1.00751003],
       [ 1.45444125, -0.6459116 ,  2.08328512],
       [-0.3535235 , -2.52013489, -1.6945886 ]])

In [80]:
np.sort(arr,axis=1)

array([[-0.93311551, -0.41702291,  0.72639504],
       [-0.42956273,  0.79619449,  0.87238245],
       [-1.18853185,  1.00751003,  2.15452682],
       [-0.6459116 ,  1.45444125,  2.08328512],
       [-2.52013489, -1.6945886 , -0.3535235 ]])

In [81]:
arr

array([[ 0.72639504, -0.41702291, -0.93311551],
       [ 0.87238245,  0.79619449, -0.42956273],
       [ 2.15452682, -1.18853185,  1.00751003],
       [ 1.45444125, -0.6459116 ,  2.08328512],
       [-0.3535235 , -2.52013489, -1.6945886 ]])

### 4.3.5 唯一值和其他逻辑集合

In [82]:
#使用np.unique返回唯一值排序后的拷贝

nmaes=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [83]:
#纯python实现

sorted(set(names))

['Bob', 'Joe', 'Will']

In [84]:
#使用np.in1d检查一个数组的值是否在另一个数组中

values=np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

方法|说明
--|--
unique(x)|求唯一值，并排序
intersect1d(x,y)|计算交集，并排序
union1d(x,y)|计算并集，并排序
in1d(x,y)|x的值是否在y中，返回一个布尔值数组
setdiff1d(x,y)|差集，在x中但不在y中的元素
setxor1d(x,y)|异或集，在x或y中，但不在x交y中的元素

# 4.4 使用数组进行文件输入和输出

In [85]:
arr=np.arange(10)
np.save('some_array', arr)

In [86]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.savez('array_archive.npz',a=arr,b=arr)

In [88]:
arch=np.load('array_archive.npz')
arch

In [89]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 4.5 线性代数

In [90]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])

x

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [92]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [93]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [94]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [95]:
#使用@用于点乘矩阵操作
np.ones(2)@x

array([5., 7., 9.])

函数|描述
--|--
diag|返回返回方阵的对角元素构成的一维数组，或者将一维数组中的元组构成一个对角方阵
dot|矩阵点乘
trace|计算迹
det|计算行列式
eig|计算特征值和特征向量
inv|计算方阵的逆矩阵
pinv|计算矩阵的Moore-Penrose伪逆
qr|计算QR分解
svd|计算奇异值分解
solve|求解Ax=b,其中A是方阵
lstsq|计算Ax=b的最小二乘解

# 4.6 伪随机数生成

In [96]:
np.random.seed(1234)

np.random.rand(10)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [97]:
np.random.rand(10)

array([0.35781727, 0.50099513, 0.68346294, 0.71270203, 0.37025075,
       0.56119619, 0.50308317, 0.01376845, 0.77282662, 0.88264119])

In [98]:
np.random.seed(1234)

np.random.rand(10)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [99]:
#使用RandomState生成一个独立于全局的随机数生成器

rng=np.random.RandomState(1234)
rng.rand(10)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

函数|描述
-|-
seed|向随机数生成器传递一个随机数种子
permutation|返回一个序列的随机排列，或返回一个乱序的整数范围序列
shuffle|对序列随机排序，并替代原序列
randint|从给定范围内抽取整数
binomial|
normal|
beta|
chisquare|
gamma|
uniform