# 5 pandas入门

## 5.1 pandas数据结构介绍

### 5.1.1 Series

In [1]:
import pandas as pd
import numpy as np

obj=pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [2]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj2=pd.Series([4,7,-5,3], index=list('dbac'))
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [5]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [6]:
obj2['a']

-5

In [7]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [8]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [9]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [10]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [11]:
'b' in obj2

True

In [12]:
'e' not in obj2

True

In [13]:
#根据字典生成Series

sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
states=['California','Ohio','Oregon','Texas']
obj4=pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [15]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [17]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [18]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
obj4+obj3

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [20]:
obj4.name='population'
obj4.index.name='state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [21]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [22]:
obj.index=['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

In [23]:
#使用等长度的列表或字典构建DataFrame

data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
      'year':[2000,2001,2002,2001,2002,2003],
      'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [24]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [25]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [26]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],
                    index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [27]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [28]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [29]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [30]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [31]:
frame2.debt=16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [32]:
#将列表或数组赋给一列时，长度必须相等

frame2.debt=range(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [33]:
val=pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])

frame2.debt=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [34]:
#frame2.eastern无法创建新的列

frame2['eastern']=frame2.state=='Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [35]:
#使用del删除列
#无法对frame2.eastern进行删除

del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [36]:
#从DataFrame选取的列是视图，而不是拷贝
#对Series的更改会映射到DataFrame中
#如果需要复制，应显示的使用Series的copy方法

series1=frame2.debt
series1[:]=8
frame2

C:\Users\liudonghang\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


year   state  pop  debt
one    2000    Ohio  1.5   8.0
two    2001    Ohio  1.7   8.0
three  2002    Ohio  3.6   8.0
four   2001  Nevada  2.4   8.0
five   2002  Nevada  2.9   8.0
six    2003  Nevada  3.2   8.0

In [37]:
#使用嵌套字典创建DataFrame

pop={'Nevada':{2001:2.4,2002:2.9},
     'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [38]:
#对索引选择与排序

pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [39]:
#包含Series的字典也可以创建DataFrame

pdata={'Ohio':frame3['Ohio'][:-1],
       'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [40]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [41]:
frame2.values

array([[2000, 'Ohio', 1.5, 8.0],
       [2001, 'Ohio', 1.7, 8.0],
       [2002, 'Ohio', 3.6, 8.0],
       [2001, 'Nevada', 2.4, 8.0],
       [2002, 'Nevada', 2.9, 8.0],
       [2003, 'Nevada', 3.2, 8.0]], dtype=object)

## 5.2 基本功能

### 5.2.1 重建索引

In [42]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [43]:
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [44]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [45]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [46]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'],
                   columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [47]:
frame.reindex(['a','b','c','d'])

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [48]:
frame.reindex(columns=['Texas','Utah','California'])

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [49]:
frame.loc[['a','b','c','d'],['Texas','Utah','California']]

C:\Users\liudonghang\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

参数|描述
-|-
method|'ffill'前向填充，'bfill'后向填充
fill_value|缺失值的替代值
limit|前向或后向填充时，所需填充的最大尺寸间隙（以元素数量）
tolerance|前后向填充时，所需填充的不精确匹配下的最大尺寸（以绝对数字距离）
level|匹配Multiindex级别的简单索引，否则为子集
copy|如果为True,新旧索引相同时复制底层数据，否则不复制

### 5.2.2 轴向上删除条目

In [50]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [51]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [52]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [53]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                  index=['Ohio','Colorado','Utah','New York'],
                  columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [54]:
#默认在axis=0上删除
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [55]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [56]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [57]:
obj.drop('c',inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 5.2.3 索引、选择与过滤

In [58]:
obj=pd.Series(range(4),index=['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int64

In [59]:
obj[1:2]

b    1
dtype: int64

In [60]:
#使用索引的名称切片包含尾部
obj['b':'c']

b    1
c    2
dtype: int64

In [61]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [62]:
#选择标量和列表对应columns
#选择切片对应index

data['three']

Ohio         2
Colorado     6
Utah        10
New York    14
Name: three, dtype: int32

In [63]:
data[['one','three']]

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [64]:
#同样，使用名称切片包含尾部

data[:'Utah']

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [65]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [66]:
data['three']>5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [67]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [68]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [69]:
data[data<5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [70]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### 5.2.3.1 使用loc和iloc选择数据 

In [71]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [72]:
data.iloc[1,[1,2]]

two      5
three    6
Name: Colorado, dtype: int32

In [73]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [74]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [75]:
data.iloc[:,:3]=99
data

one  two  three  four
Ohio       99   99     99     0
Colorado   99   99     99     7
Utah       99   99     99    11
New York   99   99     99    15

### 5.2.4 整数索引

In [76]:
#整数会引发歧义

ser=pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [77]:
#整数索引为标签索引
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [78]:
#整数索引为位置索引

ser.iloc[:1]

0    0.0
dtype: float64

In [79]:
#直接选择根据位置索引

ser[:1]

0    0.0
dtype: float64

### 5.2.5 算术和数据对齐

In [80]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [81]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [82]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [83]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),
                 index=['Ohio','Texas','Colorado'],
                 columns=list('bcd'))
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),
                 index=['Utah','Ohio','Texas','Oregon'],
                 columns=list('bde'))
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [84]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [85]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

#### 5.2.5.1 使用填充值的算术方法

In [86]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),
                 columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),
                 columns=list('abcde'))
df2.loc[1,'b']=np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [87]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [88]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [89]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [90]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

算术方法|描述
-|-
add,radd|+
sub,rsub|-
div,rdiv|/
lioordiv,rfloordiv|//
mul,rmul|*
pow,rpow|**

#### 5.2.5.2 DataFrame和Series间的操作

In [91]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                   columns=list('bde'),
                   index=['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [92]:
series=frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [93]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [94]:
series2=pd.Series(range(3),index=list('bef'))
frame-series2

b   d     e   f
Utah    0.0 NaN   1.0 NaN
Ohio    3.0 NaN   4.0 NaN
Texas   6.0 NaN   7.0 NaN
Oregon  9.0 NaN  10.0 NaN

In [95]:
#如果想在列上广播，需要使用算术方法

series3=frame['d']
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5.2.6 函数应用和映射

In [96]:
#将函数应用到每行或每列

frame=pd.DataFrame(np.random.rand(4,3),columns=list('bde'),
                   index=['Utah','Ohio','Texas','Oregon'])

f=lambda x:x.max()-x.min()

frame.apply(f)

b    0.379196
d    0.295240
e    0.826831
dtype: float64

In [97]:
frame.apply(f,axis=1)

Utah      0.480353
Ohio      0.621951
Texas     0.768028
Oregon    0.754035
dtype: float64

In [98]:
#可以将带有多个值的Series传给apply

def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f)

b         d         e
min  0.132171  0.696481  0.074530
max  0.511367  0.991720  0.901361

In [99]:
#使用applymap逐元素的格式化字符串
 
format=lambda x:'%.2f'%x
frame.applymap(format)

b     d     e
Utah    0.51  0.99  0.90
Ohio    0.49  0.70  0.07
Texas   0.20  0.97  0.66
Oregon  0.13  0.88  0.89

In [100]:
#Series有map方法

frame['e'].map(format)

Utah      0.90
Ohio      0.07
Texas     0.66
Oregon    0.89
Name: e, dtype: object

### 5.2.7 排序和排名

In [101]:
obj=pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [102]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [103]:
frame=pd.DataFrame(np.arange(8.).reshape((2,4)),
                   index=['three','one'],
                   columns=['d','a','b','c'])

frame.sort_index()

d    a    b    c
one    4.0  5.0  6.0  7.0
three  0.0  1.0  2.0  3.0

In [104]:
frame.sort_index(axis=1)

a    b    c    d
three  1.0  2.0  3.0  0.0
one    5.0  6.0  7.0  4.0

In [105]:
frame.sort_index(axis=1,ascending=False)

d    c    b    a
three  0.0  3.0  2.0  1.0
one    4.0  7.0  6.0  5.0

In [106]:
obj=pd.Series([4,7,-3,2])

obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [107]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [108]:
#使用by将一列作为排序键

frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [109]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [110]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [111]:
obj=pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [112]:
obj.rank(method='min')

0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [113]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [114]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [115]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

方法|描述
-|-
average|对相等的元素使用平均排名
min|使用最小
max|使用最大
first|按照元素在源数据中的次序排名
dense|类似于min,但组间排名总是加1，而不是相等元素数量


### 5.2.8 含有重复标签的轴索引

In [116]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [117]:
obj.index.is_unique

False

In [118]:
obj['a']

a    0
a    1
dtype: int64

# 5.3 描述性统计的概述和计算

In [119]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
                index=['a','b','c','d'],
                columns=['one','two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [120]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [121]:
df.mean(axis=1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

方法|描述
-|-
axis|
skipna|默认为True
level|多层索引下，可以缩减分组层级


In [122]:
#最大值的索引标签

df.idxmax()

one    b
two    d
dtype: object

In [123]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [124]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [125]:
obj=pd.Series(['a','a','b','c']*4)

obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [126]:
obj.value_counts()

a    8
b    4
c    4
dtype: int64

方法|描述
-|-
argmin,argmax|最小最大值的位置索引
idxmin,idxmax|最小最大值的标签索引
quantile|计算百分位数
mad|平均绝对偏差
prod|求积
cummin,cummax|累计和的最小最大值
diff|差分
pct_change|计算百分比

### 5.3.1 相关性和协方差

In [127]:
conda install pandas-datareader

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [128]:
import pandas_datareader.data as web

all_data={ticker:web.get_data_yahoo(ticker)
          for ticker in ['AAPL','IBM','MSFT','GOOG']}
price=pd.DataFrame({ticker:data['Adj Close']
                    for ticker,data in all_data.items()})
volumn=pd.DataFrame({ticker:data['Volume']
                     for ticker,data in all_data.items()})  #注：变量名写错，应为volume

In [129]:
#计算股价的百分比

returns=price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-01-13  0.021364 -0.000658  0.012024  0.006645
2020-01-14 -0.013503 -0.005710 -0.007043 -0.005802
2020-01-15 -0.004286  0.005890  0.006476  0.005815
2020-01-16  0.012526  0.009955  0.018323  0.008685
2020-01-17  0.011071  0.002392  0.005597  0.019763

In [130]:
returns['MSFT'].corr(returns['IBM'])

0.48360907937691777

In [131]:
returns['MSFT'].cov(returns['IBM'])

9.153512603759404e-05

In [132]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.398727  0.574572  0.525971
IBM   0.398727  1.000000  0.483609  0.409564
MSFT  0.574572  0.483609  1.000000  0.660175
GOOG  0.525971  0.409564  0.660175  1.000000

In [133]:
returns.corrwith(returns.IBM)

AAPL    0.398727
IBM     1.000000
MSFT    0.483609
GOOG    0.409564
dtype: float64

In [134]:
returns.corrwith(volumn)

AAPL   -0.120274
IBM    -0.132575
MSFT   -0.087870
GOOG   -0.002356
dtype: float64

In [135]:
#使用axis=1逐行地计算相关系数
#在计算前，数据已经根据标签对齐
#删去成对数据中含有NA的数对，而不会删去含有NA的整行

corr_byrow=returns.corrwith(volumn,axis=1)

In [136]:
corr_byrow.head()

Date
2015-01-20         NaN
2015-01-21   -0.034081
2015-01-22   -0.128147
2015-01-23   -0.349286
2015-01-26    0.327537
dtype: float64

### 5.3.2 唯一值、计数和成员属性

In [137]:
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])

obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [138]:
#分类计数，自动降序排列

obj.value_counts()  

c    3
a    3
b    2
d    1
dtype: int64

In [139]:
#value_counts也是pandas的顶层方法

pd.value_counts(obj,sort=False)

a    3
c    3
b    2
d    1
dtype: int64

In [140]:
pd.value_counts(obj.values,sort=False)

a    3
c    3
b    2
d    1
dtype: int64

In [141]:
mask=obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [142]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [143]:
np.in1d(obj,['b','c'])

array([ True, False, False, False, False,  True,  True,  True,  True])

In [144]:
mask2=np.in1d(obj,['b','c'])
obj[mask2]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [145]:
#使用Index。get_indexer方法得到一个索引数组
#根据一个唯一值数组的索引，将另一个非唯一值数组转化

to_match=pd.Series(['c','a','b','b','c','a'])
unique_vals=pd.Series(['c','b','a'])

pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [146]:
#对于DataFrame对象分类计数，综合每一列的值

data=pd.DataFrame({'Qu1':[1,3,4,3,4],
                   'Qu2':[2,3,1,2,3],
                   'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [147]:
data.apply(pd.value_counts).fillna(0)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [148]:
data.apply(pd.value_counts,axis=1).fillna(0)

1    2    3    4    5
0  2.0  1.0  0.0  0.0  0.0
1  0.0  0.0  2.0  0.0  1.0
2  1.0  1.0  0.0  1.0  0.0
3  0.0  1.0  1.0  1.0  0.0
4  0.0  0.0  1.0  2.0  0.0